version: "3.9"
services:

  app:
    image: earthrobot/devops-for-programmers-project-lvl1:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.production
    command: 'npm test'
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    user: "1000:1000"
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data